### ISSUE TITLE
How do I access this in grasshopper?

### ISSUE THREAD

**Issue by SteveScott** [mcneel/glTFLib#11]
How do I access this from grasshopper? Do I build the solution in Visual Studio? When will this be incorporated into Rhino 7?

**Comment by fraguada** [comment]
@SteveScott This is a repository that includes several submodules needed to build a library that contains classes and serialization and desrialization of glb/gltf data. It has no specific ties to Rhino, but would be the base for a Rhino plugin or Grasshopper add-on.

> Do I build the solution in Visual Studio?

Yes.

> When will this be incorporated into Rhino 7?

Check this plugin: https://github.com/Stykka/glTF-Bin
